version: '3.0'
services:
  postgresql:
    container_name: postgresql_container
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  backend:
    container_name: backend_container
    image: backend:1.0.0
    restart: always
    depends_on: 
      - postgresql
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DB_HOST=postgresql
      - DB_SCHEMA=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    links:
      - postgresql

volumes:
  postgresql: