version: '3'
services:
  wordpress:
    container_name: servidor_web
    image: wordpress
    restart: always
    environments:
     - WORDPRESS_DB_HOST=servidor_mysql 
     - WORDPRESS_DB_USER=user_wp 
     - WORDPRESS_DB_PASSWORD=pass_wp 
     - WORDPRESS_DB_NAME=db_wp

    ports:
      - 82:80
    volumes:
      - wp_vol:/var/www/html/wp-content
    networks:
      - wp_net

  mysql:
    container_name: servidor_mysql
    image: mysql
    restart: always
    environments:
     - MYSQL_DATABASE=db_wp 
     - MYSQL_USER=user_wp 
     - MYSQL_PASSWORD=pass_wp 
     - MYSQL_ROOT_PASSWORD=pass_wp

    ports:
      - 82:80
    volumenes:
      - mysql_vol:/var/www/html/wp_content