apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks8web-deploy
  labels:
    app: ks8
    tier: frontend
  annotations:
    kubernetes.io/change-cause: "roxsross12/k8s_test_web:v1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ks8
      tier: frontend
  template:
    metadata:
      labels:
        app: ks8
        tier: frontend
    spec:
      containers:
        - name: imagen-ks8
          image: roxsross12/k8s_test_web:v1
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80