apiVersion: v1
kind: Service
metadata:
  name: service-flask
  labels:
    app: service-flask
    tier: backend
spec:
  type: NodePort
  hostname:
  selector:
    app: service-flask
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 8000
