version: '3.0'
services:
  webapp:
    container_name: webapp
    image: python-web:1.0.0
    restart: always 
    ports:
      - 8080:80
    depends_on:
      - redis
    networks:
      - 08_net

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
     - 6379:6379
    networks:
     - 08_net

networks:
  08_net:
    driver: bridge