FROM nginx
LABEL project=demo
WORKDIR /app
COPY html/ /usr/share/nginx/html

#registry/nombre_imagen:etiqueta
#cdongoh/nginx-web:1.0.1
#docker build -t nginx-web:1.0.1 .
#docker tag nginx-web:1.0.1 cdongoh/nginx-web:1.0.1
#docker push cdongoh/nginx-web:1.0.1 