apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deploy
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
       app: guestbook
       tier: frontend
    spec:
      containers:
      - name: imagen-guestbook
        image: roxsross12/guestbook
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000

##investigar de 